/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 bean_bot.glb --transform 
Files: bean_bot.glb [12.52MB] > bean_bot-transformed.glb [3.8MB] (70%)
Author: nataliedesign (https://sketchfab.com/nataliedesign)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bean-bot-9b1c86da128147e59bdbb9092ad40d2e
Title: Bean Bot
*/

import React, {useLayoutEffect, useRef} from 'react'
import {useGLTF, useScroll} from '@react-three/drei'
import {useFrame} from "@react-three/fiber";
import gsap from "gsap";

export function Robot2(props) {
  const { nodes, materials } = useGLTF('./models/robot/bean_bot-transformed.glb')
    const robotRef = useRef();
    const scroll = useScroll();
    const timeline = useRef();

    useFrame((state, delta) => {
        timeline.current.seek(scroll?.offset * timeline.current.duration())
    })

    useLayoutEffect(()=> {
        timeline.current = gsap.timeline({defaults: {duration: 2, ease: 'power1.inOut'}});

        timeline.current
            .to(robotRef?.current.rotation, {y: -1}, 2)
            .to(robotRef?.current.position, {x: 1}, 2)

            .to(robotRef?.current.rotation, {y: 1}, 6)
            .to(robotRef?.current.position, {x: -1}, 6)

            .to(robotRef?.current.rotation, {y: 0}, 11)
            .to(robotRef?.current.rotation, {x: 1}, 11)
            .to(robotRef?.current.position, {x: 0}, 11)

            .to(robotRef?.current.rotation, {y: 0}, 13)
            .to(robotRef?.current.rotation, {x: -1}, 13)
            .to(robotRef?.current.position, {x: 0}, 13)

            .to(robotRef?.current.rotation, {y: 0}, 16)
            .to(robotRef?.current.rotation, {x: 0}, 16)
            .to(robotRef?.current.position, {x: 0}, 16)

            .to(robotRef?.current.rotation, {y: 0}, 20)
            .to(robotRef?.current.rotation, {x: 0}, 20)
            .to(robotRef?.current.position, {x: 0}, 20)

    },[])
    console.log(materials);
    return (
        <group {...props} dispose={null} ref={robotRef}>
            <mesh
                geometry={nodes.Sweep_Grey_0.geometry}
                material={materials.Grey}
            />
            <mesh
                geometry={nodes.Sweep_1_Blue_0.geometry}
                material={materials.Blue}
            />
            <mesh
                geometry={nodes.Sweep_2_Brown_0.geometry}
                material={materials.Brown}
            />
            <mesh
                geometry={nodes.Sweep_3_Green_0.geometry}
                material={materials.Green}
            />
            <mesh
                geometry={nodes.Sweep_4_Red_0.geometry}
                material={materials.material}
            />
            <mesh
                geometry={nodes.Group24954_1_BeanBot_0.geometry}
                material={materials.BeanBot}
                position={[-0.018, 0.72, 0.506]}
            />
        </group>
    );
}

useGLTF.preload('./models/robot/bean_bot-transformed.glb')
